### ISSUE TITLE
Tag picker doesn’t support multiple selections

### ISSUE THREAD

**Issue by Gerzer** [rcos/rcos_io#151]
Selecting a new tag in the tag picker in the project editor deselects any previously selected tags, making it impossible to add more than one tag to a project.

**Comment by bnidevs** [comment]
@Apexal

**Comment by Apexal** [comment]
This uses the native select component with the multiple attribute, allowing for selection of multiple while holding down control. I'll either add help text making this clear, or switch to checkboxes. Good call out!

**Comment by Gerzer** [comment]
I‘m a little surprised that the native `<select>` component is so unintuitive on mainstream platforms. There is value in using native components, so perhaps clearly visible help text could be a good compromise. (Checkboxes may be more intuitive without help text, but they don’t scale well as you add more options, and there are already a large number of options as-is.)

**Comment by Apexal** [comment]
Added help test describing how to select multiple.

**Comment by Gerzer** [comment]
Thanks!
