### ISSUE TITLE
Allow project leads to remove students from team

### ISSUE THREAD

**Issue by Tripplenut** [rcos/rcos_io#156]
Project Leads have the ability to add any student to their team using their RCS ID but having an option to remove them as well would be nice. Some potential ways to do this is a "Remove" button under the "Add" button in the Add Team Member box:
<img src="https://github.com/rcos/rcos_io/assets/67553651/68127df3-1b30-4cb2-910f-be5834d9febc" alt="fig1" width="100"/>

Another way to solve this problem would be a little boot next to the student name on the tile:
<img src="https://github.com/rcos/rcos_io/assets/67553651/4ccc8599-5e13-4d7b-b1d3-297b64c33523" alt="fig2" width="300">

**Comment by Apexal** [comment]
Great suggestion. This is an important feature. I'll add this tonight or tomorrow.
