### ISSUE TITLE
Email-change functionality is broken

### ISSUE THREAD

**Issue by Gerzer** [rcos/rcos_io#30]
The functionality to change your sign-in email is broken. In my experience, it fails with a generic error message roughly 50% of the time. When it doesn’t fail outright, it creates a _new_ user account instead of replacing the email in the existing account. The new account seems to have no link to the existing one, and it doesn’t inherit any Discord connections or project membership. Additionally, the new account isn’t marked as RPI-affiliated even when the existing account used an “@rpi.edu” email address.

**Comment by Apexal** [comment]
Removing this functionality in favor of social login
