### ISSUE TITLE
Attendance form is poorly designed

### ISSUE THREAD

**Issue by Gerzer** [rcos/rcos_io#31]
To submit the attendance code for a meeting, the user must already know to press the “return” key on their keyboard because there’s no visual affordance. This is nonobvious and poorly designed. There should be an explicit “Submit” button (or similar/equivalent). That said, there’s no reason to remove the ability to bypass such a button by pressing the “return” key.

**Comment by Apexal** [comment]
Good call! Fixing shortly.
