### ISSUE TITLE
Page titles

### ISSUE THREAD

**Issue by Apexal** [rcos/rcos_io#51]
Using a Django Template Language [`block`](https://docs.djangoproject.com/en/4.1/ref/templates/language/#template-inheritance), we can easily set the `<title>` attribute on pages so we get tab titles like `Projects | RCOS IO`, `Frank M '22 (matraf) | RCOS IO`. Note that we'll want a default title of `RCOS IO`.

**Comment by bnidevs** [comment]
ez

**Comment by bnidevs** [comment]
will also add ogp tags

adding to `ogp` branch
