### ISSUE TITLE
Saving Small Group Meeting Tab

### ISSUE THREAD

**Issue by Tripplenut** [rcos/rcos_io#95]
I've been running into Qol problem with the small group tab not saving on refresh. Just a heads up I know nothing about web development.

So lets say I'm looking at my small group attendance during a meeting and I have the tab selected like this
<img  src="https://user-images.githubusercontent.com/67553651/218213384-86c7dbac-b058-48e1-9cb8-3441684bf8a5.png" alt="image1" width="400"/>

When I then decided to refresh after verifying attendance for a student the tab then switched over to all students, like this
<img src="https://user-images.githubusercontent.com/67553651/218213919-329bca82-5a70-4bbc-afd3-2198c7268885.png" alt="image2" width="400" >

I would then need to re-click on sage 2112 to verify the next student and repeat the process all over again. It's minor but annoying enough for me to make an issue about it. Thanks in advance!

**Comment by Tripplenut** [comment]
I was doing the verification on mobile btw

**Comment by Apexal** [comment]
This isn't minor at all, that's super annoying! Great catch. I'll fix this ASAP for the next meeting.
